version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    groups:
      test-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "nl.jqno.equalsverifier:equalsverifier"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    groups:
      gh-actions:
        patterns:
          - "*"
